require 'spec_helper'

describe Certman do
  it 'has a version number' do
    expect(Certman::VERSION).not_to be nil
  end

  it '3 < FQDN.length < 25 generated by certman' do
    domain = '63.example.com'
    expect(Certman::Client.new(domain).send(:bucket_name)).to eq '63.example.com-generated-by-certman-for-ses-inbound-'
  end

  it '25 =< FQDN.length < 54 generated by certman' do
    domain = '63.characters.long.example.com'
    expect(Certman::Client.new(domain).send(:bucket_name)).to eq '63.characters.long.example.com-certman-'
  end

  it '54 =< FQDN.length generated by certman' do
    domain = '012345678901234567890123456789012345678901.example.com'
    expect(Certman::Client.new(domain).send(:bucket_name)).to eq '18e184175db0713c0f7e21159061ad07efe695ed-certman-'
  end
end
