require 'spec_helper'

describe Certman do
  it 'has a version number' do
    expect(Certman::VERSION).not_to be nil
  end

  context 'S3 bucket name limitation' do
    it '3 =< FQDN.length < 54 generated by certman' do
      domain = '63.example.com'
      expected = '63.example.com-certman'
      expect(Certman::Client.new(domain).send(:bucket_name)).to eq expected

      domain = '63.characters.long.example.com'
      expected = '63.characters.long.example.com-certman'
      expect(Certman::Client.new(domain).send(:bucket_name)).to eq expected
    end

    it '54 =< FQDN.length generated by certman' do
      domain = '0123456789012345678901234567890123456789012.example.com'
      expected = '7c0326349f8377cea67ea8752e9dcdb0c2442ac2-certman'
      expect(Certman::Client.new(domain).send(:bucket_name)).to eq expected
    end
  end

  context 'SES rule name limitation' do
    it '3 =< FQDN.length < 51 generated by certman' do
      domain = '64.example.com'
      expected = 'RuleCertman_64.example.com'
      expect(Certman::Client.new(domain).send(:rule_name)).to eq expected
    end

    it '51 =< FQDN.length generated by certman' do
      domain = '0123456789012345678901234567890123456789.example.com'
      expected = 'RuleCertman_ddb217d92c02b447e714a5af0f380d98c6e12cf4'
      expect(Certman::Client.new(domain).send(:rule_name)).to eq expected
    end
  end

  context 'SES rule name limitation' do
    it '3 =< FQDN.length < 51 generated by certman' do
      domain = '64.example.com'
      expected = 'RuleSetCertman_64.example.com'
      expect(Certman::Client.new(domain).send(:rule_set_name)).to eq expected
    end

    it '48 =< FQDN.length generated by certman' do
      domain = '0123456789012345678901234567890123456.example.com'
      expected = 'RuleSetCertman_6c923105446eef2b7d58f8cb117400c4058a9758'
      expect(Certman::Client.new(domain).send(:rule_set_name)).to eq expected
    end
  end
end
